FROM python:3.9-alpine as pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install pipenv to convert Pipfile to requirements.txt
RUN pip3 install --no-cache-dir --upgrade pipenv; \
    pipenv requirements > requirements.txt

FROM python:3.9-alpine as builder

# Copy requirements.txt from pipenv
COPY --from=pipenv /requirements.txt requirements.txt

# Install gcc for building python dependencies; Install dependencies
RUN apk add --no-cache build-base; \
    pip3 install --no-cache-dir -r requirements.txt

# Create base image for running TCM
FROM python:3.9-alpine
LABEL maintainer="CollinHeist" \
      description="Automated title card maker for Plex"

# Set working directory, copy source into container
WORKDIR /maker
COPY . /maker

# Copy python packages from builder
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

# Script environment variables
ENV TCM_PREFERENCES=/config/preferences.yml \
    TCM_IS_DOCKER=TRUE

# Delete setup files
# Replace gosu with su-exec
# Install su-exec in place of gosu, imagemagick, shadow for group/user add
# Create user and group to run the container
# Override default ImageMagick policy XML file
RUN rm Pipfile Pipfile.lock; \
    sed -i 's/gosu/su-exec/g' start.sh; \
    apk add --no-cache su-exec imagemagick shadow; \
    groupadd -g 314 titlecardmaker; \
    useradd -u 314 -g 314 titlecardmaker; \
    cp modules/ref/policy.xml /etc/ImageMagick-7/policy.xml

# Entrypoint
CMD ["python3", "main.py", "--run", "--no-color"]
ENTRYPOINT ["sh", "./start.sh"]