site_name: TitleCardMaker
site_url: https://titlecardmaker.com/
site_author: Collin Heist
site_description: >-
  Automated Title Card creator for Plex, Emby, and Jellyfin.

repo_name: CollinHeist/TitleCardMaker
repo_url: https://github.com/CollinHeist/TitleCardMaker
edi_uri: edit/web-ui/docs/

theme:
  logo: ./assets/logo.svg
  favicon: ./assets/favicon.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # SPA instant navigation
    - navigation.instant
    # Show progress bar on slow connections
    - navigation.instant.progress
    # Linked content tabs
    - content.tabs.link
    # Update URL anchors with current location
    - navigation.tracking
    # Navigation bar/menu
    - navigation.tabs
    - navigation.tabs.sticky
    # Render table of contents as part of navbar
    - toc.integrate
    # Back to top buttom
    - navigation.top
    # Add bottom next/previous nav buttons
    - navigation.footer
    # Index page for nav subsections
    - navigation.indexes
    # Copy code button
    - content.code.copy
    # Code annotations
    - content.code.annotate
    # Add "edit" and "view" docs actions
    # - content.action.edit
    # - content.action.view
  font:
    text: Roboto
    code: Roboto Mono
  # icon:
  #   logo: ./assets/logo.svg

plugins:
  # Enable site search
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

  - glightbox:
      width: 65%
      skip_classes:
        - no-lightbox
  
  # Enable animated code terminals
  - termynal:
      title: Command Line

  # Enable social cards
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: rgb(29, 29, 29)

# Hooks
hooks:
  - docs/overrides/hooks/shortcodes.py

extra:
  # Social links on the footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CollinHeist/TitleCardMaker
      name: TitleCardMaker GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bJ3bHtw8wH
      name: TitleCardMaker Discord
    - icon: fontawesome/solid/heart
      class: md-social__link
      link: https://github.com/sponsors/CollinHeist
      name: Become a Sponsor


extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  # Abbreviations
  - abbr
  - attr_list
  - pymdownx.snippets

  # Admonitions
  - admonition
  - pymdownx.details

  # Annotations
  # - attr_list
  - md_in_html
  - pymdownx.superfences

  # Checklists
  - pymdownx.tasklist:
      custom_checkbox: true

  # Definition lists https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - def_list

  # Icons
  # - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # - pymdownx.snippets
  - pymdownx.superfences

  # Footnotes
  - footnotes

  # Markdown extensions
  # - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # Tables
  - tables

  # Adding keyboard keys
  - pymdownx.keys

  # Embedding files, auto-include a glossary
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md

nav:
  - Home: index.md
  - Getting Started:
    - getting_started/index.md
    - Terminology: getting_started/terminology.md
    # - Installation - Docker:
    #   - getting_started/docker/index.md
    #   - Docker: getting_started/docker/docker.md
    #   - Docker Compose: getting_started/docker/compose.md
    #   - Synology DSM: getting_started/docker/synology.md
    #   - UnRAID: getting_started/docker/unraid.md
    # - Installation - Local: getting_started/local.md
    - Importing YAML Settings: getting_started/import_settings.md
    - Configuring Connections:
      - getting_started/connections/index.md
      - Emby: getting_started/connections/emby.md
      - Jellyfin: getting_started/connections/jellyfin.md
      - Plex: getting_started/connections/plex.md
      - Sonarr: getting_started/connections/sonarr.md
      - Tautulli: getting_started/connections/tautulli.md
      - TMDb: getting_started/connections/tmdb.md
    - Global Settings: getting_started/settings.md
    - Creating a Font: getting_started/custom_font.md
    - Creating Templates: getting_started/creating_templates.md
    - Adding a Series: getting_started/add_series.md
    - Creating the First Sync:
      - getting_started/first_sync/index.md
      - Emby: getting_started/first_sync/emby.md
      - Jellyfin: getting_started/first_sync/jellyfin.md
      - Plex: getting_started/first_sync/plex.md
      - Sonarr: getting_started/first_sync/sonarr.md
    - Rescheduling Tasks: getting_started/scheduler.md
    - Creating Title Cards: getting_started/creating_cards.md
  - Blueprints: blueprints.md
  - User Guide:
    - user_guide/index.md
    - Series: user_guide/series.md
    - Adding Series: user_guide/new_series.md
    - Templates: user_guide/templates.md
    - Fonts: user_guide/fonts.md
    # - Sync: user_guide/sync.md
    - Settings: user_guide/settings.md
    - Connections: user_guide/connections.md
    - Scheduler: user_guide/scheduler.md
    - Variables: user_guide/variables.md
    # - Importer: user_guide/importer.md
    - Logs: user_guide/logs.md
    - Setting Priority: user_guide/setting_priority.md
    # - FAQ: user_guide/faq.md
  - Card Types:
    # - card_types/index.md
    - Local: card_types/local.md
    #   - Anime: card_types/local/anime.md
    #   - Cutout: card_types/local/cutout.md
    #   - Divider: card_types/local/divider.md
    #   - Fade: card_types/local/fade.md
    #   - Frame: card_types/local/frame.md
    #   - Landscape: card_types/local/landscape.md
    #   - Logo: card_types/local/logo.md
    #   - Olivier: card_types/local/olivier.md
    #   - Poster: card_types/local/poster.md
    #   - Roman Numeral: card_types/local/roman_numeral.md
    #   - Standard: card_types/local/standard.md
    #   - Star Wars: card_types/local/star_wars.md
    #   - Textless: card_types/local/textless.md
    #   - Tinted Frame: card_types/local/tinted_frame.md
    #   - Tinted Glass: card_types/local/tinted_glass.md
  - Development:
    - Contributing: development/contributing.md
    - The API: development/api.md
  - Help & Support: help_and_support.md