site_name: TitleCardMaker
site_url: ''
site_author: Collin Heist
site_description: >-
  Automated title card creator for Plex, Emby, and Jellyfin.

repo_name: CollinHeist/TitleCardMaker
repo_url: https://github.com/CollinHeist/TitleCardMaker

theme:
  logo: ./assets/logo512.png
  favicon: ./assets/favicon.ico
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # SPA instant navigation
    - navigation.instant
    # Linked content tabs
    - content.tabs.link
    # Navigation bar/menu
    # - navigation.tabs
    # - navigation.tabs.sticky
    # Back to top buttom
    - navigation.top
    # Add bottom next/previous nav buttons
    - navigation.footer
    # Index page for nav subsections
    - navigation.indexes
    # Copy code button
    - content.code.copy
    # Code annotations
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true

extra:
  # Social links on the footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CollinHeist/TitleCardMaker
      name: TitleCardMaker GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bJ3bHtw8wH
      name: TitleCardMaker Discord

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  # Abbreviations
  - abbr
  - attr_list
  - pymdownx.snippets

  # Admonitions
  - admonition
  - pymdownx.details

  # Annotations
  # - attr_list
  - md_in_html
  - pymdownx.superfences

  # Definition lists https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - def_list

  # Icons
  # - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # - pymdownx.snippets
  - pymdownx.superfences

  # Markdown extensions
  # - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # Tables
  - tables

  # Adding keyboard keys
  - pymdownx.keys

  # Embedding files, auto-include a glossary
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md

nav:
  - Home: index.md
  - Getting Started - Tutorial:
    - Installation - Docker:
      - getting_started/docker/index.md
      - Docker: getting_started/docker/docker.md
      - UnRAID: getting_started/docker/unraid.md
      - Synology DSM: getting_started/docker/synology.md
    - Installation - Local: getting_started/local.md
    - Importing YAML Settings: getting_started/import_settings.md
    - Configuring Connections:
      - getting_started/connections/index.md
      - Emby: getting_started/connections/emby.md
      - Jellyfin: getting_started/connections/jellyfin.md
      - Plex: getting_started/connections/plex.md
      - Sonarr: getting_started/connections/sonarr.md
      - Tautulli: getting_started/connections/tautulli.md
    - Global Settings: getting_started/settings.md
    - Creating Templates: getting_started/creating_templates.md
    - Adding a Series: getting_started/add_series.md
    - Creating the First Sync:
      - getting_started/first_sync/index.md
      - Emby: getting_started/first_sync/emby.md
      - Jellyfin: getting_started/first_sync/jellyfin.md
      - Plex: getting_started/first_sync/plex.md
      - Sonarr: getting_started/first_sync/sonarr.md
    - Rescheduling Tasks: getting_started/scheduler.md
    - Creating Title Cards: getting_started/creating_cards.md
  - Settings: settings.md

  - API: api.md
  - Release Notes: release_notes.md