name: Docker Develop Release

on:
  push:
    branches: [ develop ]

jobs:
  docker-develop:
    uses: CollinHeist/TitleCardMaker/.github/workflows/docker_build.yml
    with:
      tag: develop
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}