name: Docker Develop Release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  docker-develop:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/titlecardmaker:develop
      
      - name: Build imagemagick
        uses: docker/build-push-action@v4
        with:
          context: ./docker/imagick
          platforms: linux/amd64,linux/arm64
          push: false
          tags: imagemagick-builder:latest
    
      - name: Build and push alpine
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/titlecardmaker:develop-alpine
