name: Docker Master Release

on:
  push:
    branches: [ master ]

jobs:
  docker-master:
    uses: ./.github/workflows/docker_build.yml
    with:
      tag: master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  docker-master-armv7:
    uses: ./.github/workflows/docker_build_armv7.yml
    with:
      tag: master-armv7
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
