name: Update Documentation
on:
  push:
    branches:
      - web-ui

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # - run: echo "cache_id=$(date --utc '+%F')" >> $GITHUB_ENV 

      # - uses: actions/cache@v3
      #   with:
      #     key: mkdocs-material-${{ env.cache_id }}
      #     path: .cache
      #     restore-keys: |
      #       mkdocs-material-

      - uses: actions/checkout@master
        with:
          repository: CollinHeist/mkdocs-material
          path: ./mkdocs

      - run: cd mkdocs && python -m pip install .[imaging]

      - run: mkdocs gh-deploy --force
