name: Update Documentation
on:
  push:
    branches:
      - web-ui

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/checkout@master
        with:
          repository: CollinHeist/mkdocs-material
          path: ./mkdocs

      - run: cd mkdocs && python -m pip install .[imaging] termynal==0.11.1 mkdocs-glightbox==0.3.4

      - run: mkdocs gh-deploy --force
